services:
  app:
    container_name: branda-server
    build:
      context: .
    ports:
      - '3000:3000'

  brandaTestDB:
    image: postgres:16
    container_name: brandaTestDB
    ports:
      - "8002:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./testDB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mainDB:
  testDB:
